name: build-apk

on:
  push:
    tags:
      - 'v*'
    branches: [ main, master ]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # JDK 21：构建 libxposed/api -> mavenLocal
      - name: Set up JDK 21 (for libxposed/api)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Bootstrap Gradle 8.7 and generate wrapper
        run: |
          GRADLE_VERSION=8.7
          wget -q https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
          unzip -q gradle-${GRADLE_VERSION}-bin.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-${GRADLE_VERSION}/bin" >> $GITHUB_PATH
          gradle --version
          gradle wrapper --gradle-version ${GRADLE_VERSION}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true

      - name: Install required Android packages
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      - name: Fetch libxposed api (api:100) and publish to mavenLocal
        run: |
          mkdir -p external
          git clone --depth=1 https://github.com/libxposed/api.git external/libxposed-api
          ./gradlew -p external/libxposed-api publishToMavenLocal

      # 切回 JDK 17：编译 App（不在 Gradle 内签名）
      - name: Set up JDK 17 (for app)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Publish libxposed api to mavenLocal
        run: |
          git clone --depth=1 https://github.com/libxposed/api.git
          cd api
          ./gradlew publishToMavenLocal

      - name: Build
        run: ./gradlew clean assembleRelease

      - name: Build Release APK
        run: ./gradlew --no-daemon assembleRelease

      - name: List APK outputs (debug)
        run: ls -lah app/build/outputs/apk/release || true

      # === 签名（仅在 tag 构建）===
      - name: Decode PKCS12 keystore
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 -d > release.p12
          ls -lh release.p12

      - name: Zipalign & Sign APK (pkcs12)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          ALIAS: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          STORE_PASS: ${{ secrets.ANDROID_SIGNING_STORE_PASS }}
          KEY_PASS: ${{ secrets.ANDROID_SIGNING_KEY_PASS }}
        run: |
          set -e
          UNSIGNED=$(ls app/build/outputs/apk/release/*-unsigned.apk | head -n1)
          echo "Unsigned APK: $UNSIGNED"

          ZIPALIGN="$ANDROID_HOME/build-tools/35.0.0/zipalign"
          APKSIGNER="$ANDROID_HOME/build-tools/35.0.0/apksigner"

          mkdir -p release
          $ZIPALIGN -v -p 4 "$UNSIGNED" release/app-aligned.apk

          $APKSIGNER sign \
            --ks release.p12 \
            --ks-type PKCS12 \
            --ks-key-alias "$ALIAS" \
            --ks-pass pass:"$STORE_PASS" \
            --key-pass pass:"$KEY_PASS" \
            --out "release/MiFitnessAmapNavFix-${GITHUB_REF_NAME}.apk" \
            release/app-aligned.apk

          $APKSIGNER verify -v "release/MiFitnessAmapNavFix-${GITHUB_REF_NAME}.apk"
          (cd release && sha256sum *.apk > SHA256SUMS.txt)

      - name: Publish GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.apk
            release/SHA256SUMS.txt
          generate_release_notes: true

      - name: Upload artifact (CI only, not tagged)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: MiFitnessAmapNavFix-APK
          path: app/build/outputs/apk/release/*-unsigned.apk
